driver=org.postgresql.Driver

url=jdbc:postgresql://postgres:${POSTGRES_CONTAINER_PORT}/${POSTGRES_DB}
username=${POSTGRES_USER}
password=${POSTGRES_PASSWORD}

changeLogFile=changelog/changelog-master.yaml
searchPath=/workspace

logLevel=INFO
