driver=org.postgresql.Driver

url=jdbc:postgresql://postgres:${POSTGRES_CONTAINER_PORT}/${POSTGRES_DB}
username=${MIGRATOR_DB_USER}
password=${MIGRATOR_DB_PASSWORD}

changeLogFile=changelog/changelog-master.yaml
searchPath=/workspace

logLevel=INFO
